name: SDF Validation
run-name: validate
on:
  push:
    branches: [main]
jobs:
  sdf-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sdf-install
        with:
          ns-account-id: ${{ secrets.NETSUITE_ACCOUNT_ID }}
          ns-token-id: ${{ secrets.NETSUITE_TOKEN_ID }}
          ns-token-secret: ${{ secrets.NETSUITE_TOKEN_SECRET }}
      - name: Deploy project to ${{ secrets.NETSUITE_ACCOUNT_ID }}
        run: npm run deploy