name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          jdk-version : '11.0.24'

      - name: Install SuiteCloud CLI
        run: npm install -g --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli

      - name: Authenticate with NetSuite
        run: suitecloud account:savetoken --account TD2938052  --authid mfgfund-prod --tokenid af36a4f664ea2c705e5abf97497d1c29fb482a2b3242aafb7c32e3bd7d1ff607  --tokensecret bc977fd8bf2e35eaa89dfa1cb93a3eecd997114816793f130046017f8bfcb195

      - name: Deploy to NetSuite
        run: suitecloud project:deploy