name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Debug - Node.js version
        run: node --version

      - name: Debug - NPM version
        run: npm --version

      - name: Install SuiteCloud CLI
        run: npm install -g @oracle/suitecloud-cli

      - name: Debug - SuiteCloud CLI version
        run: suitecloud --version

      - name: Authenticate with NetSuite
        env:
          NETSUITE_ACCOUNT_ID: ${{ secrets.NETSUITE_ACCOUNT_ID }}
          NETSUITE_AUTH_ID: ${{ secrets.NETSUITE_AUTH_ID }}
        run: suitecloud account:login --account $NETSUITE_ACCOUNT_ID --authid $NETSUITE_AUTH_ID

      - name: Deploy to NetSuite
        run: suitecloud project:deploy
