name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Java 8
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk
          
      - name: Verify Java Version
        run: java -version
          
      - name: Install SuiteCloud CLI
        run: npm install -g --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli

      - name: Authenticate with NetSuite
        env:
          NETSUITE_ACCOUNT_ID: ${{ secrets.NETSUITE_ACCOUNT_ID }}
          NETSUITE_AUTH_ID: ${{ secrets.NETSUITE_AUTH_ID }}
          NETSUITE_TOKEN_ID: ${{ secrets.NETSUITE_TOKEN_ID }}
          NETSUITE_TOKEN_SECRET: ${{ secrets.NETSUITE_TOKEN_SECRET }}
        run: suitecloud account:savetoken --account $NETSUITE_ACCOUNT_ID --authid $NETSUITE_AUTH_ID --tokenid $NETSUITE_TOKEN_ID --tokensecret $NETSUITE_TOKEN_SECRET

      - name: Debug - SuiteCloud CLI version
        run: suitecloud --version

      - name: Deploy to NetSuite
        run: suitecloud project:deploy
