name: Deploying to QA
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy
    runs-on: 
container:
  image: vickcam/suitecloud-cli-node:1.0
    steps:
      - run: suitecloud account:ci --savetoken --account ${{ secrets.NETSUITE_ACCOUNT_ID }} --authid ${{ secrets.NETSUITE_AUTH_ID }} --tokenid ${{ secrets.NETSUITE_TOKEN_ID }} --tokensecret ${{ secrets.NETSUITE_TOKEN_SECRET }}
      - run: suitecloud project:validate
      - run: suitecloud project:deploy